
vocab: 
  tokenizer_type: wordpiece
  tokenizer: 
    vocab: ./wordpiece/vocab.txt
    lowercase: false
    strip_accents: false
    clean_text: false
  vocab_path: ./vocab_hash.npy

train:
  dataset_type: QQPDataset
  labels: [neg, pos] 
  tensorboard_path: ./logs/qqp
  log_interval_steps: 10
  epochs: 15
  train_batch_size: 256
  test_batch_size: 256
  num_workers: 8
  max_seq_len: &max_seq_len 128
  optimizer: 
    lr: 5e-4
    betas: [0.9, 0.999]
    eps: 1e-8 

model:
  projection:
    num_hashes: 64
    feature_size: &feature_size 1024
  bottleneck:
    feature_size: *feature_size
    hidden_dim: &hidden_dim 256
  mixer: 
    num_mixers: 2
    max_seq_len: *max_seq_len
    hidden_dim: *hidden_dim
    mlp_hidden_dim: 256
  sequence_cls: 
    hidden_dim: *hidden_dim
    proj_dim: *hidden_dim
    num_classes: 2
